apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hystrix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hystrix
    spec:
      containers:
      - name: hystrix
        image: hystrix:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
